-- Trigger 
-- it is a block of Code that autometicaly execute when event(Update,Delete) happen.
-- This Triggers are store in Database

-- Data Integrity Enforcement: Triggers can enforce complex business rules and integrity constraints that standard SQL constraints 
-- (like foreign keys or check constraints) cannot. They can validate data before insertion or update, ensuring only valid data is stored.
-- Automation: Triggers automate routine tasks by executing predefined actions in response to specified events (e.g., INSERT, UPDATE, DELETE, CREATE, LOGON). This reduces the need for manual intervention and ensures consistency across operations.
-- Auditing and Logging: They are highly effective for creating automatic audit trails of data changes. Triggers can log who made a change, what was changed, and when, which is crucial for security, compliance, and troubleshooting.
-- Centralized Business Logic: Triggers allow for the centralization of business logic within the database. This ensures that the rules are applied consistently, regardless of the application used to access the data

-- Syntax --
-- Create 
-- Before / After
-- update / Delete / Insert
-- create table emp_copy
-- as
-- Select employee_id , first_name from hr.employees where employee_id 
-- between 100 and 105;

-- select * from emp_copy;

-- create or replace trigger emp_trigger_1
-- after update
-- on emp_copy

-- begin 
--     DBMS_OUTPUT.PUT_LINE('Trigger');
-- end;

-- There are two Types of Trigger
-- Row Level Trigger and Statement Level Trigger

-- create or replace trigger emp_trigger_1
-- after update or insert
-- on emp_copy
-- for each row
-- begin 
--     if updating THEN
--     DBMS_OUTPUT.PUT_LINE('Update');
--     else DBMS_OUTPUT.PUT_LINE('Insert');
--     end if;
-- end;

-- CREATE TABLE audits (
--       audit_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--       table_name       VARCHAR2(255),
--       transaction_name VARCHAR2(10),
--       by_user          VARCHAR2(30),
--       transaction_date DATE
-- );

-- create or replace trigger emp_trigger_1
-- after update or insert
-- on emp_copy
-- for each row
-- DECLARE
--    l_transaction VARCHAR2(10);
-- BEGIN
--    -- determine the transaction type
--   if updating then 
--      l_transaction := 'Update';
--      elsif deleting then 
--      l_transaction := 'delete';
--      end if;
--    -- insert a row into the audit table   
--    INSERT INTO audits (table_name, transaction_name, by_user, transaction_date)
--    VALUES('Emp_copy', l_transaction, USER, SYSDATE);
-- END;

-- CREATE TABLE audit2 (
--       Old_Name         varchar(200),
--       New_name         VARCHAR2(255)    
-- );

create or replace trigger emp_trigger_1
after update or insert
on emp_copy
for each row
DECLARE
   l_transaction VARCHAR2(10);
BEGIN
   -- determine the transaction type
  if updating then 
     l_transaction := 'Update';
     elsif deleting then 
     l_transaction := 'delete';
     end if;
   -- insert a row into the audit table   
   INSERT INTO audits (table_name, transaction_name, by_user, transaction_date)
   VALUES('Emp_copy', l_transaction, USER, SYSDATE);
END;